### ISSUE TITLE
Missing bricks in first frame after load_equalizer change

### ISSUE THREAD

**Issue by eile** [BlueBrain/Livre#62]
Some bricks are missing for one frame when the load_eq changes the tiling, even though they should be on GPU memory.

**Comment by eile** [comment]
Can be observed easily with the default Dynamic2D layout on a multi-GPU machine

**Comment by bilgili** [comment]
This issue is a result of having one dash tree per node. Each channel is modifying the same dash tree according to their own view. We tried with multiple nodes (means multiple dash trees) and it is working with "Dynamic2D" config.

The solution is to have a dash context per channel. In current architecture this is possible using multiple connections from/to dash processors but in this case the triggering of the right input/right output should be tracked.

If we are going to switch from dash ( where I will vote for that ) to boost::future, boost::async  and threadpool based pipeline implementation, this is not necessary for now.

**Comment by bilgili** [comment]
@eile :  can you check this is still an issue for you ? I have tested with Dynamic2D, Static2D configs, it look like it is working fine.

**Comment by eile** [comment]
Confirmed, works.
